<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9c3f71663060f39193502c835d60f3e7
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9c3f71663060f39193502c835d60f3e7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9c3f71663060f39193502c835d60f3e7::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
